version: '3.8'
services:
  mongo:
    image: mongo:6.0.4
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - graylog

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Dlog4j2.formatMsgNoLookups=true -Xms512m -Xmx512m"
    ports:
      - 9200:9200
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - graylog

  graylog:
    depends_on:
      - mongo
      - elasticsearch
    image: graylog/graylog:5.0
    environment:
      # Refer to server.conf for all available options
      # https://go2docs.graylog.org/5-0/setting_up_graylog/server.conf.html
      
      # General
      ## Recommend changing this to a unique value
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
      - GRAYLOG_ROOT_USERNAME=admin
      ## Password: admin
      ### Change this password in production!
      ### Use https://www.scopulus.co.uk/tools/passwordmastersha2.htm or another tool to generate a SHA2 hash
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      # Web & REST API
      ## Recommend! Enabling HTTPS
      - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9000/

      # Using Defaults for the following options:
      ## Elasticsearch
      ## Rotation
      ## MongoDB
      ## Email
      ## HTTP
      ## Processing Status
      ## Script Alert Notification
      ## Others
    entrypoint: /usr/bin/tini -- wait-for-it elasticsearch:9200 -- /docker-entrypoint.sh
    restart: always
    ports:
      - 9000:9000 # Web Interface
      - 514:514/udp # Syslog UDP
      - 5044:5044 # WinLog Beat
    volumes:
      - graylog_data:/usr/share/graylog/data
    networks:
      - graylog

# Defines Docker volumes for the Graylog stack to persist data between restarts
volumes:
  mongo_data:
    driver: local
  es_data:
    driver: local
  graylog_data:
    driver: local

# Define the networks used by the Graylog stack
networks:
  graylog:
    driver: bridge